server:
  port: 8080
logging:
  level:
    liquibase: DEBUG
spring:
  apllication:
    name: conjunto
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:19272/railway
    username: postgres
    password: mXHOBHpPvlHMbPDJvlxBslajcheLBFHI
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

