
server:
  port: 8090
logging:
  level:
    org:
      hibernate:
        type: trace
spring:
  apllication:
    name: conjunto
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:19272/railway
    username: postgres
    password: mXHOBHpPvlHMbPDJvlxBslajcheLBFHI
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

